name: Build + Deploy

on:
  push:
    branches: [ 'main' ]
#    paths:
#      - ".github/workflows/deployment.yml"
#      - "libis/**"
#      - "manifests/**"
#      - "scripts/**"
#      - ".iiifrc.yml"
#      - "bun.lockb"

jobs:
  build:
    runs-on: ubuntu-latest

    name: Node ${{ matrix.node }} build
    steps:
      - uses: actions/checkout@v1

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: actions/cache@v3
        with:
          path: .iiif/cache
          key: ${{ runner.os }}-${{ hashFiles('.iiifrc.yml') }}

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build
